### ISSUE TITLE
binds only work when focused?

### ISSUE THREAD

**Issue by Disastorm** [Elephant42/FS_Tool#4]
I was trying this out with a generic gamepad and it seems the binds only work when FS_Tool is focused? Is this intended? So I can't use it if I'm focusing MSFS2020?

**Comment by Elephant42** [comment]
I'm sorry but I can't reproduce this behavior.  I have tested with all the USB devices I have available - 8 in all - and they all work as intended.

**Comment by Disastorm** [comment]
weird, i can even do it outside of msfs, like if i just focus a random window, the joystick button presses don't show up in the fs tool. I can record a video but I guess that probably wont help you if it doesnt happen to you.
Hm might be an issue with this gamepad i guess, it seems the windows built-in usb gamepad button checker thing doesnt work out of focus either.

**Comment by Disastorm** [comment]
Ok I confirmed my button box works fine with it which is what I was going to use it for anyway.
It seems for whatever reason the issue is only with some third party xbox one usb gamepad I got awhile back, which I don't actually care about I was just using it for testing.

**Comment by Disastorm** [comment]
Hey do I need to install some kind of bridge for some of the events?

**Comment by Elephant42** [comment]
Yes - it's all in the readme - you need the MobiFlight WASM modules to get all the unsupported events such as G1000 etc.
The readme details where to get it.

**Comment by Disastorm** [comment]
alright thanks

**Comment by Disastorm** [comment]
FYI
by pure coincidence i happened to see this post that actually explains the issue with the xbox controllers with a different tool, but guessing it was the case here, too.

https://www.reddit.com/r/hotas/comments/krcr1y/joystick_gremlin_wont_start_macro_from_xbox/gieugja/?context=3
